#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/8264229Q/work ensure=absent force=true;
puppet resource file /tmp/8264229Q/ ensure=absent force=true;
puppet resource file /tmp/8264229Q ensure=directory;
puppet resource file /tmp/8264229Q/work ensure=directory;
cd /tmp/8264229Q/work
git clone https://github.com/jianliangh/poc_repo.git
cp -p /tmp/8264229Q/work/poc_repo2/8264229Q_index.html /var/www/html/index.html
